version: 2.1
workflows:
  my-workflow:
    jobs:
      - build:
          context:
            - dockerhub_credentials
      - test:
          context:
            - dockerhub_credentials

executors:
  master:
    docker:
      - image: dawidblom/ci-cd:latest
        auth:
          username: $DOCKERHUB_USERNAME 
          password: $DOCKERHUB_PASSWORD 


jobs:
  build:
    executor: master
    steps:
      - checkout
      - run:
          name: Building Project
          command: |
            mkdir build
            cmake -S . -B build
            cmake --build build
      - run:
          name: Execute Main 
          command: ./build/main
  
  test:
    executor: master
    steps:
      - checkout
      - run:
          name: Building Unit Tests 
          command: |
            cd test
            echo $(cat ~/.bashrc)
            echo $PATH
          #  echo $CPPUTEST_HOME
          #  make -f Makefile libra_test
     # - run:
          #name: Execute Unit Tests
          #command: ./test/libra_test -c -v

