version: 2.1
executors:
  master:
    docker:
      - image: dawidblom/ci-cd:latest
        auth:
          username: dawidblom 
          password: DRBlom2022@!

jobs:
  build:
    executor: master
    steps:
      - checkout
      - run:
          name: Building Project
          command: |
            mkdir build
            cmake -S . -B build
          #  cmake --build build
     # - run:
     #     name: Execute Main 
     #     command: ./build/main
  
  test:
    executor: master
    steps:
      - run:
          name: Building Unit Tests 
          command: |
            ls ~/project
            
            #cd test
            
            #make -f Makefile libra_test
     # - run:
          #name: Execute Unit Tests
          #command: ./test/libra_test -c -v
workflows:
  version: 2
  build:
    jobs:
      - build
      - test
