version: 2.1
workflows:
  my-workflow:
    jobs:
      - build:
          context:
            - dockerhub_credentials
executors:
  master:
    docker:
      - image: dawidblom/ci-cd:latest
        auth:
          username: $DOCKERHUB_USERNAME 
          password: DRBlom2022@! 


jobs:
  build:
    executor: master
    steps:
      - checkout
      - run:
          name: Building Project
          command: |
            mkdir build
            cmake -S . -B build
            cmake --build build
      - run:
          name: Execute Main 
          command: ./build/main
  
  test:
    executor: master
    steps:
      - run:
          name: Building Unit Tests 
          command: |
            make -f Makefile libra_test
     # - run:
          #name: Execute Unit Tests
          #command: ./test/libra_test -c -v
#workflows:
#  my-workflow:
#    jobs:
#     - build
#      - test
